package mega.privacy.mobile.analytics.event

import mega.privacy.mobile.analytics.annotations.NotificationEvent

@NotificationEvent
interface GenericAppPushNotificationReceived

@NotificationEvent
interface GenericAppPushNotificationTapped

@NotificationEvent
interface FullStorageOverQuotaBannerDisplayed

@NotificationEvent
interface AlmostFullStorageOverQuotaBannerDisplayed

@NotificationEvent
interface NotificationCentreItemTapped

@NotificationEvent
interface MonthlyPlanPurchaseSuccessful

@NotificationEvent
interface MonthlyPlanPurchaseFailed

@NotificationEvent
interface AnnualPlanPurchaseSuccessful

@NotificationEvent
interface AnnualPlanPurchaseFailed

@NotificationEvent
interface TwoYearPlanPurchaseSuccessful

@NotificationEvent
interface TwoYearPlanPurchaseFailed